// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dialog.proto

package dialog

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type UrlNameRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UrlNameRequest) Reset()         { *m = UrlNameRequest{} }
func (m *UrlNameRequest) String() string { return proto.CompactTextString(m) }
func (*UrlNameRequest) ProtoMessage()    {}
func (*UrlNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dialog_d1bf8b59d83f694b, []int{0}
}
func (m *UrlNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UrlNameRequest.Unmarshal(m, b)
}
func (m *UrlNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UrlNameRequest.Marshal(b, m, deterministic)
}
func (dst *UrlNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UrlNameRequest.Merge(dst, src)
}
func (m *UrlNameRequest) XXX_Size() int {
	return xxx_messageInfo_UrlNameRequest.Size(m)
}
func (m *UrlNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UrlNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UrlNameRequest proto.InternalMessageInfo

func (m *UrlNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type UrlNameReply struct {
	Url                  string   `protobuf:"bytes,1,opt,name=Url,proto3" json:"Url,omitempty"`
	StatusCode           int32    `protobuf:"varint,2,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	PingTime             int64    `protobuf:"varint,3,opt,name=PingTime,proto3" json:"PingTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UrlNameReply) Reset()         { *m = UrlNameReply{} }
func (m *UrlNameReply) String() string { return proto.CompactTextString(m) }
func (*UrlNameReply) ProtoMessage()    {}
func (*UrlNameReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_dialog_d1bf8b59d83f694b, []int{1}
}
func (m *UrlNameReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UrlNameReply.Unmarshal(m, b)
}
func (m *UrlNameReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UrlNameReply.Marshal(b, m, deterministic)
}
func (dst *UrlNameReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UrlNameReply.Merge(dst, src)
}
func (m *UrlNameReply) XXX_Size() int {
	return xxx_messageInfo_UrlNameReply.Size(m)
}
func (m *UrlNameReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UrlNameReply.DiscardUnknown(m)
}

var xxx_messageInfo_UrlNameReply proto.InternalMessageInfo

func (m *UrlNameReply) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *UrlNameReply) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *UrlNameReply) GetPingTime() int64 {
	if m != nil {
		return m.PingTime
	}
	return 0
}

type MaxMinPingReply struct {
	Max                  *MaxMinPingReply_PhoneNumber `protobuf:"bytes,1,opt,name=Max,proto3" json:"Max,omitempty"`
	Min                  *MaxMinPingReply_PhoneNumber `protobuf:"bytes,2,opt,name=Min,proto3" json:"Min,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *MaxMinPingReply) Reset()         { *m = MaxMinPingReply{} }
func (m *MaxMinPingReply) String() string { return proto.CompactTextString(m) }
func (*MaxMinPingReply) ProtoMessage()    {}
func (*MaxMinPingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_dialog_d1bf8b59d83f694b, []int{2}
}
func (m *MaxMinPingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaxMinPingReply.Unmarshal(m, b)
}
func (m *MaxMinPingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaxMinPingReply.Marshal(b, m, deterministic)
}
func (dst *MaxMinPingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaxMinPingReply.Merge(dst, src)
}
func (m *MaxMinPingReply) XXX_Size() int {
	return xxx_messageInfo_MaxMinPingReply.Size(m)
}
func (m *MaxMinPingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MaxMinPingReply.DiscardUnknown(m)
}

var xxx_messageInfo_MaxMinPingReply proto.InternalMessageInfo

func (m *MaxMinPingReply) GetMax() *MaxMinPingReply_PhoneNumber {
	if m != nil {
		return m.Max
	}
	return nil
}

func (m *MaxMinPingReply) GetMin() *MaxMinPingReply_PhoneNumber {
	if m != nil {
		return m.Min
	}
	return nil
}

type MaxMinPingReply_PhoneNumber struct {
	Url                  string   `protobuf:"bytes,1,opt,name=Url,proto3" json:"Url,omitempty"`
	PingTime             int64    `protobuf:"varint,3,opt,name=PingTime,proto3" json:"PingTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaxMinPingReply_PhoneNumber) Reset()         { *m = MaxMinPingReply_PhoneNumber{} }
func (m *MaxMinPingReply_PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*MaxMinPingReply_PhoneNumber) ProtoMessage()    {}
func (*MaxMinPingReply_PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_dialog_d1bf8b59d83f694b, []int{2, 0}
}
func (m *MaxMinPingReply_PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaxMinPingReply_PhoneNumber.Unmarshal(m, b)
}
func (m *MaxMinPingReply_PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaxMinPingReply_PhoneNumber.Marshal(b, m, deterministic)
}
func (dst *MaxMinPingReply_PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaxMinPingReply_PhoneNumber.Merge(dst, src)
}
func (m *MaxMinPingReply_PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_MaxMinPingReply_PhoneNumber.Size(m)
}
func (m *MaxMinPingReply_PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_MaxMinPingReply_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_MaxMinPingReply_PhoneNumber proto.InternalMessageInfo

func (m *MaxMinPingReply_PhoneNumber) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *MaxMinPingReply_PhoneNumber) GetPingTime() int64 {
	if m != nil {
		return m.PingTime
	}
	return 0
}

type RequestStatReply struct {
	RequestStat1         []*UrlNameReply    `protobuf:"bytes,1,rep,name=RequestStat1,proto3" json:"RequestStat1,omitempty"`
	RequestStat2         []*MaxMinPingReply `protobuf:"bytes,2,rep,name=RequestStat2,proto3" json:"RequestStat2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RequestStatReply) Reset()         { *m = RequestStatReply{} }
func (m *RequestStatReply) String() string { return proto.CompactTextString(m) }
func (*RequestStatReply) ProtoMessage()    {}
func (*RequestStatReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_dialog_d1bf8b59d83f694b, []int{3}
}
func (m *RequestStatReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestStatReply.Unmarshal(m, b)
}
func (m *RequestStatReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestStatReply.Marshal(b, m, deterministic)
}
func (dst *RequestStatReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestStatReply.Merge(dst, src)
}
func (m *RequestStatReply) XXX_Size() int {
	return xxx_messageInfo_RequestStatReply.Size(m)
}
func (m *RequestStatReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestStatReply.DiscardUnknown(m)
}

var xxx_messageInfo_RequestStatReply proto.InternalMessageInfo

func (m *RequestStatReply) GetRequestStat1() []*UrlNameReply {
	if m != nil {
		return m.RequestStat1
	}
	return nil
}

func (m *RequestStatReply) GetRequestStat2() []*MaxMinPingReply {
	if m != nil {
		return m.RequestStat2
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_dialog_d1bf8b59d83f694b, []int{4}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*UrlNameRequest)(nil), "dialog.UrlNameRequest")
	proto.RegisterType((*UrlNameReply)(nil), "dialog.UrlNameReply")
	proto.RegisterType((*MaxMinPingReply)(nil), "dialog.MaxMinPingReply")
	proto.RegisterType((*MaxMinPingReply_PhoneNumber)(nil), "dialog.MaxMinPingReply.PhoneNumber")
	proto.RegisterType((*RequestStatReply)(nil), "dialog.RequestStatReply")
	proto.RegisterType((*Empty)(nil), "dialog.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	GetInfo(ctx context.Context, in *UrlNameRequest, opts ...grpc.CallOption) (*UrlNameReply, error)
	GetMaxMinPing(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MaxMinPingReply, error)
	RequestStat(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RequestStatReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) GetInfo(ctx context.Context, in *UrlNameRequest, opts ...grpc.CallOption) (*UrlNameReply, error) {
	out := new(UrlNameReply)
	err := c.cc.Invoke(ctx, "/dialog.Greeter/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetMaxMinPing(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MaxMinPingReply, error) {
	out := new(MaxMinPingReply)
	err := c.cc.Invoke(ctx, "/dialog.Greeter/GetMaxMinPing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) RequestStat(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RequestStatReply, error) {
	out := new(RequestStatReply)
	err := c.cc.Invoke(ctx, "/dialog.Greeter/RequestStat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// Sends a greeting
	GetInfo(context.Context, *UrlNameRequest) (*UrlNameReply, error)
	GetMaxMinPing(context.Context, *Empty) (*MaxMinPingReply, error)
	RequestStat(context.Context, *Empty) (*RequestStatReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UrlNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dialog.Greeter/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetInfo(ctx, req.(*UrlNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetMaxMinPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetMaxMinPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dialog.Greeter/GetMaxMinPing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetMaxMinPing(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_RequestStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).RequestStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dialog.Greeter/RequestStat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).RequestStat(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dialog.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _Greeter_GetInfo_Handler,
		},
		{
			MethodName: "GetMaxMinPing",
			Handler:    _Greeter_GetMaxMinPing_Handler,
		},
		{
			MethodName: "RequestStat",
			Handler:    _Greeter_RequestStat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dialog.proto",
}

func init() { proto.RegisterFile("dialog.proto", fileDescriptor_dialog_d1bf8b59d83f694b) }

var fileDescriptor_dialog_d1bf8b59d83f694b = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x5f, 0x4b, 0x32, 0x41,
	0x14, 0xc6, 0x1d, 0xf7, 0x55, 0xdf, 0xce, 0x6a, 0xc9, 0x21, 0x6a, 0xd9, 0x8b, 0x58, 0xa6, 0x2e,
	0xf6, 0x4a, 0x68, 0x23, 0x50, 0xbc, 0x8c, 0x90, 0x2e, 0x14, 0xd9, 0xf2, 0xae, 0x9b, 0x15, 0x4f,
	0xb6, 0xb0, 0x3b, 0x63, 0xe3, 0x08, 0xfa, 0x11, 0xfa, 0x48, 0x41, 0x1f, 0x2e, 0x76, 0xfc, 0xd3,
	0x6a, 0x1a, 0xdd, 0xcd, 0x79, 0x78, 0x1e, 0x9e, 0xdf, 0x39, 0x0c, 0x54, 0x47, 0x71, 0x94, 0xc8,
	0x71, 0x63, 0xa2, 0xa4, 0x96, 0x58, 0x5e, 0x4e, 0xfc, 0x0a, 0x8e, 0x07, 0x2a, 0xe9, 0x45, 0x29,
	0x85, 0xf4, 0x36, 0xa3, 0xa9, 0x46, 0x84, 0x7f, 0x22, 0x4a, 0xc9, 0x61, 0x1e, 0xf3, 0x8f, 0x42,
	0xf3, 0xe6, 0xcf, 0x50, 0xdd, 0xb8, 0x26, 0xc9, 0x02, 0xeb, 0x60, 0x0d, 0x54, 0xb2, 0xb2, 0x64,
	0x4f, 0xbc, 0x00, 0x78, 0xd4, 0x91, 0x9e, 0x4d, 0xef, 0xe4, 0x88, 0x9c, 0xa2, 0xc7, 0xfc, 0x52,
	0x98, 0x53, 0xd0, 0x85, 0xff, 0xfd, 0x58, 0x8c, 0x9f, 0xe2, 0x94, 0x1c, 0xcb, 0x63, 0xbe, 0x15,
	0x6e, 0x66, 0xfe, 0xc9, 0xe0, 0xa4, 0x1b, 0xcd, 0xbb, 0xb1, 0xc8, 0xa4, 0x65, 0xc3, 0x2d, 0x58,
	0xdd, 0x68, 0x6e, 0x1a, 0xec, 0xe0, 0xb2, 0xb1, 0x62, 0xdf, 0x71, 0x35, 0xfa, 0xaf, 0x52, 0x50,
	0x6f, 0x96, 0x0e, 0x49, 0x85, 0x99, 0xdf, 0xc4, 0x62, 0x61, 0xfa, 0xff, 0x1c, 0x8b, 0x85, 0xdb,
	0x06, 0x3b, 0xa7, 0xed, 0x59, 0xef, 0x37, 0xfc, 0x77, 0x06, 0xf5, 0xd5, 0xf1, 0xb2, 0x85, 0x97,
	0xfc, 0x4d, 0xa8, 0xe6, 0xb4, 0x6b, 0x87, 0x79, 0x96, 0x6f, 0x07, 0xa7, 0x6b, 0xa2, 0xfc, 0x35,
	0xc3, 0x2d, 0x27, 0xb6, 0xb7, 0x92, 0x81, 0x53, 0x34, 0xc9, 0xf3, 0x03, 0xbb, 0x6c, 0x85, 0x03,
	0x5e, 0x81, 0xd2, 0x7d, 0x3a, 0xd1, 0x8b, 0xe0, 0x83, 0x41, 0xa5, 0xa3, 0x88, 0x34, 0x29, 0x6c,
	0x41, 0xa5, 0x43, 0xfa, 0x41, 0xbc, 0x48, 0x3c, 0xfb, 0x01, 0x60, 0xc2, 0xee, 0x5e, 0x30, 0x5e,
	0xc0, 0x16, 0xd4, 0x3a, 0xa4, 0xbf, 0x3b, 0xb1, 0xb6, 0x36, 0x9a, 0x1a, 0xf7, 0x10, 0x16, 0x2f,
	0x60, 0x13, 0xec, 0x1c, 0xda, 0x6e, 0xd0, 0x59, 0x8f, 0xbb, 0x97, 0xe3, 0x85, 0x61, 0xd9, 0x7c,
	0xd1, 0x9b, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x08, 0xe5, 0xd7, 0xfb, 0xb2, 0x02, 0x00, 0x00,
}
